src/main/java/com/othr/kucko/paydudekucko/entity/Address.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import javax.persistence.Embeddable;

/**
 *
 * @author kucko
 */
@Embeddable
public class Address {
    private String street;
    private String number;
    private String postalCode;
    private String city;
    
    public Address(){
        
    }

    public Address(String street, String number, String postalCode, String city) {
        this.street = street;
        this.number = number;
        this.postalCode = postalCode;
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
    
    
    
}

src/main/java/com/othr/kucko/paydudekucko/entity/BankAccount.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import java.io.Serializable;
import javax.persistence.Entity;


/**
 *
 * @author kucko
 */
@Entity
public class BankAccount extends SingleIdEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private String Owner;
    private String IBAN;

    public BankAccount() {
    }

    public BankAccount(String Owner, String IBAN) {
        this.Owner = Owner;
        this.IBAN = IBAN;
    }
    
    public String getOwner() {
        return Owner;
    }

    public void setOwner(String Owner) {
        this.Owner = Owner;
    }

    public String getIBAN() {
        return IBAN;
    }

    public void setIBAN(String IBAN) {
        this.IBAN = IBAN;
    }
    
}

src/main/java/com/othr/kucko/paydudekucko/entity/Customer.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 *
 * @author kucko
 */
@Entity
@Table(uniqueConstraints = @UniqueConstraint(columnNames = {"email"}))
public class Customer extends SingleIdEntity implements Serializable {
    
    @OneToOne(fetch=FetchType.EAGER)
    private PaydudeAccount account;
    @OneToMany
    private List<InternalTransaction> internalTransactions;
    @OneToMany
    private List<ExternalTransaction> externalTransactions;
    
    private String firstName;
    private String lastName;
    private String password;
    private String email;
    private Address address; // TODO: 

    public Customer(String firstName, String lastName, String email, String password, Address address) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.password = password;
        this.email = email;
        this.address = address;
        this.internalTransactions = new ArrayList<>();
        this.externalTransactions = new ArrayList<>();
    }

    public Customer() {
    }

    public PaydudeAccount getAccount() {
        return account;
    }

    public void setAccount(PaydudeAccount account) {
        this.account = account;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public List<InternalTransaction> getInternalTransactions() {
        return internalTransactions;
    }

    public void setInternalTransactions(List<InternalTransaction> internalTransactions) {
        this.internalTransactions = internalTransactions;
    }

    public List<ExternalTransaction> getExternalTransactions() {
        return externalTransactions;
    }

    public void setExternalTransactions(List<ExternalTransaction> externalTransactions) {
        this.externalTransactions = externalTransactions;
    }
    
    public void addInternalTransaction(InternalTransaction it) {
        this.internalTransactions.add(it);
    }
    
    public void addExternalTransaction(ExternalTransaction et) {
        this.externalTransactions.add(et);
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public Address getAddress() {
        return address;
    }

    public void setAddress(Address address) {
        this.address = address;
    }
    
}

src/main/java/com/othr/kucko/paydudekucko/entity/ExternalTransaction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author kucko
 */
@Entity
public class ExternalTransaction extends SingleIdEntity implements Serializable {

    private static final long serialVersionUID = 1L;
    @ManyToOne(fetch=FetchType.EAGER)
    private PaydudeAccount sender;
    private String receiverIBAN;
    @Temporal(TemporalType.DATE)
    private Date transactionDate;
    private long amount;

    public ExternalTransaction() {
        this.transactionDate = new Date();
    }

    public ExternalTransaction(PaydudeAccount sender, String receiverIBAN, long amount) {
        this.sender = sender;
        this.receiverIBAN = receiverIBAN;
        this.amount = amount;
        this.transactionDate = new Date();
    }

    
    
    public PaydudeAccount getSender() {
        return sender;
    }

    public void setSender(PaydudeAccount sender) {
        this.sender = sender;
    }

    public String getReceiverIBAN() {
        return receiverIBAN;
    }

    public void setReceiverIBAN(String receiverIBAN) {
        this.receiverIBAN = receiverIBAN;
    }

    public Date getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    public long getAmount() {
        return amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }
    
}

src/main/java/com/othr/kucko/paydudekucko/entity/InternalTransaction.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 *
 * @author kucko
 */
@Entity
public class InternalTransaction extends SingleIdEntity implements Serializable {

    private static final long serialVersionUID = 1L;
    @ManyToOne(fetch=FetchType.EAGER)
    private PaydudeAccount sender;
    @ManyToOne(fetch=FetchType.EAGER)
    private PaydudeAccount receiver;
    @Temporal(TemporalType.DATE)
    private Date transactionDate;
    private long amount;

    public InternalTransaction() {
        this.transactionDate = new Date();
    }

    public InternalTransaction(PaydudeAccount sender, PaydudeAccount receiver, long amount) {
        this.sender = sender;
        this.receiver = receiver;
        this.amount = amount;
        this.transactionDate = new Date();
    }

    public PaydudeAccount getSender() {
        return sender;
    }

    public void setSender(PaydudeAccount sender) {
        this.sender = sender;
    }

    public PaydudeAccount getReceiver() {
        return receiver;
    }

    public void setReceiver(PaydudeAccount receiver) {
        this.receiver = receiver;
    }

    public Date getTransactionDate() {
        return transactionDate;
    }

    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }

    public long getAmount() {
        return amount;
    }

    public void setAmount(long amount) {
        this.amount = amount;
    }
    
}

src/main/java/com/othr/kucko/paydudekucko/entity/PaydudeAccount.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import java.io.Serializable;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 *
 * @author kucko
 */
@Entity
public class PaydudeAccount implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @OneToOne(mappedBy="account", fetch=FetchType.EAGER)
    private Customer Owner;
    @OneToOne(fetch=FetchType.EAGER)
    private BankAccount bankAccount;
    private long balance;
    
    public PaydudeAccount() {
        this.balance = 0;
    }

    public Customer getOwner() {
        return Owner;
    }

    public void setOwner(Customer Owner) {
        this.Owner = Owner;
    }

    public BankAccount getBankAccount() {
        return bankAccount;
    }

    public void setBankAccount(BankAccount bankAccount) {
        this.bankAccount = bankAccount;
    }

    public long getBalance() {
        return balance;
    }

    public void setBalance(long balance) {
        this.balance = balance;
    }
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof PaydudeAccount)) {
            return false;
        }
        PaydudeAccount other = (PaydudeAccount) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return id + ": " + Owner.getFirstName() + " " + Owner.getLastName();
    }
    
}

src/main/java/com/othr/kucko/paydudekucko/entity/SingleIdEntity.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.entity;

import java.util.Objects;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.MappedSuperclass;

/**
 *
 * @author kucko
 */
@MappedSuperclass
public class SingleIdEntity {
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    @Override
    public int hashCode() {
        int hash = 3;
        hash = 79 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SingleIdEntity other = (SingleIdEntity) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "SingleIdEntity{" + "id=" + id + '}';
    }
    
}

src/main/java/com/othr/kucko/paydudekucko/servlet/MyServlet.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.othr.kucko.paydudekucko.servlet;

import com.othr.kucko.paydudekucko.entity.Customer;
import com.othr.kucko.paydudekucko.service.CustomerService;
import java.io.IOException;
import java.io.PrintWriter;
import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author kucko
 */
public class MyServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    
    @Inject
    CustomerService cs;
    
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet MyServlet</title>");            
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet MyServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

src/main/webapp/account.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    <h:head>
        <title>Account Creation</title>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.min.js"></script>
        <link rel="stylesheet" media="screen" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.min.css"></link>
    </h:head>
    <h:body>
        <nav class="ui inverted menu">
            <header class="header item"> Home </header>
            <div class="right menu top attached">
                <h:form>
                    <h:commandLink class="item" action="#{customerModel.logout()}" value="Logout"/>
                </h:form>
            </div>
        </nav>
        <div class="ui segment container">
            Please enter your Bank Account information.
            <div class="ui grid">
                <div class="five wide column"></div>
                <div class="ui raised segment six wide column fluid form">
                    <h:form>
                        <div class="field">
                        IBAN: 
                        <h:inputText value="#{customerModel.iban}" class="ui input" required="true" requiredMessage="IBAN must not be empty"/>
                        </div>
                        <div class="field">
                        Owner: 
                        <h:inputText value="#{customerModel.owner}" class="ui input" required="true" requiredMessage="Owner must not be empty"/>
                        </div>
                        <h:commandButton value="Submit" action="#{customerModel.createBankAccount()}" class="ui submit button"/>
                    </h:form>
                </div>
                <div class="five wide column"></div>
            </div>
        </div>
    </h:body>
</html>

src/main/webapp/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Home</title>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.min.js"></script>
        <link rel="stylesheet" media="screen" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.1.6/semantic.min.css"></link>
    </h:head>
    <h:body>
        <nav class="ui inverted menu">
            <header class="header item"> Home </header>
            <div class="right menu top attached">
                <h:form>
                    <h:commandLink class="item" action="#{customerModel.logout()}" value="Logout"/>
                </h:form>
            </div>
        </nav>
        <section class="ui raised segment grid">
            <aside class="ui two wide column">
                <div>                
                    <h:outputText value="#{customerModel.customer.firstName}"/>
                    <h:outputText value=" "/>
                    <h:outputText value="#{customerModel.customer.lastName}"/>
                </div>
                <div>
                    Current Balance:
                    <h:outputText value="#{customerModel.balance / 100}"/>€
                </div>
            </aside>
            <article class="ui ten wide column"> Recent Transactions:
                <div class="ui grid">
                    <div class="ui nine wide column">
                        Internal:
                        <div class="raised segment" style="height: 600px; overflow-y: scroll">
                            <h:dataTable var="i" value="#{customerModel.it}" styleClass="ui celled table">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Sender"/>
                                    </f:facet>
                                    <h:outputText value="#{i.sender.owner.firstName}"/>
                                    <h:outputText value=" "/>
                                    <h:outputText value="#{i.sender.owner.lastName}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Receiver"/>
                                    </f:facet>
                                    <h:outputText value="#{i.receiver.owner.firstName}"/>
                                    <h:outputText value=" "/>
                                    <h:outputText value="#{i.receiver.owner.lastName}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Amount"/>
                                    </f:facet>
                                    <h:outputText value="#{i.amount / 100} €"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Date"/>
                                    </f:facet>
                                    <h:outputText value="#{i.transactionDate.date}"/>
                                    <h:outputText value="-"/>
                                    <h:outputText value="#{i.transactionDate.month + 1}"/>
                                    <h:outputText value="-"/>
                                    <h:outputText value="#{i.transactionDate.year + 1900}"/>
                                </h:column>
                            </h:dataTable>
                        </div>
                    </div>
                    <div class="ui seven wide column">
                        External:
                        <div class="raised segment" style="height: 600px; overflow-y: scroll;">
                            <h:dataTable var="e" value="#{customerModel.et}" styleClass="ui celled table">
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Receiver IBAN"/>
                                    </f:facet>
                                    <h:outputText value="#{e.receiverIBAN}"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Amount"/>
                                    </f:facet>
                                    <h:outputText value="#{e.amount / 100}€"/>
                                </h:column>
                                <h:column>
                                    <f:facet name="header">
                                        <h:outputText value="Date"/>
                                    </f:facet>
                                    <h:outputText value="#{e.transactionDate.date}"/>
                                    <h:outputText value="-"/>
                                    <h:outputText value="#{e.transactionDate.month}"/>
                                    <h:outputText value="-"/>
                                    <h:outputText value="#{e.transactionDate.year}"/>
                                </h:column>
                            </h:dataTable>
                        </div>
                    </div>
                </div>
            </article>
            <article class="ui four wide column">
                Create new Transaction
                <div class="right menu tabular top attached">
                    <button class="item button" data-tab="internal" onclick="$.tab('change tab', 'internal');;">Internal Transaction</button>
                    <button class="item button" data-tab="external" onclick="$.tab('change tab', 'external');">External Transaction</button>
                </div>
                <div name="internal" class="ui active bottom attached tab segment container" data-tab="internal">
                    <div class="ui raised segment fluid form">
                        <h:form>
                            <div class="field">
                                Receiver:
                                <h:selectOneMenu value="#{customerModel.receiverAccount}">
                                    <f:converter binding="#{customerModel.converter}"/>
                                    <f:selectItems value="#{customerModel.accountList}"/>
                                </h:selectOneMenu>
                                </div>
                            <div class="field">
                                Amount: 
                                <h:inputText value="#{customerModel.amount}" class="ui input" required="true" requiredMessage="Amount must not be empty or negeative"/>
                            </div>
                            <h:commandButton value="Submit Transaction" action="#{customerModel.makeInternalTransaction()}" class="ui submit button"/>
                        </h:form>
                    </div>
                </div>
                <div name="external" class="ui bottom attached tab segment container" data-tab="external">
                    <div class="ui raised segment fluid form">
                        <h:form>
                            <div class="field">
                                IBAN: 
                                <h:inputText value="#{customerModel.recvIBAN}" required="true" requiredMessage="IBAN must not be empty" class="ui input"/> <br/>
                            </div>
                            <div class="field">
                                Amount: 
                                <h:inputText value="#{customerModel.amount}" required="true" requiredMessage="Amount must not be empty or negative" class="ui input"/>
                            </div>
                            <div class="field">
                                Usage:
                                <h:inputText value="#{customerModel.usage}" required="false" class="ui input"/>
                            </div>
                            <h:commandButton value="Submit Transaction" action="#{customerModel.makeExternalTransaction()}" class="ui submit button"/>
                        </h:form>
                    </div>
                </div>
            </article>
        </section>
    </h:body>
</html>